### ISSUE TITLE
API v2 feature todo list

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#59]
- [ ] Provide actual usage guide, how-to examples, etc
- [ ] Document serializer fields with help_text
- [ ] Include auth endpoints in swagger UI
- [x] ~~Improve performance of global monster-instance and rune-instance lists~~
- [ ] Filter fields for global monster-instance endpoints
- [ ] Filter fields for global rune-instance endpoints
- [x] ~~Add global team endpoint after team model revamp~~
- [ ] Admin writeable bestiary for editing purposes
- [ ] Data log endpoints
- [ ] Personal data log endpoints underneath profiles (account owner only) w/ filtering support
- [x] Import/export endpoints
- [ ] Feedback endpoints
- [x] API key support for authorizing third party tools
- [ ] Classify existing API as v1 version in DRF
- [ ] Switch to JSON rendering only with drf-ujson-renderer (swagger UI will provide the API testing feature)

**Comment by Nicktho** [comment]
Really looking forward to 
> Import/export endpoints

I can add auto update functionality to sw-exporter

**Comment by syamantaknaskar** [comment]
Why not use Spring Framework for the REST endpoints ? I can contribute for that.

**Comment by PeteAndersen** [comment]
The website is Python based and using the Django framework. I am not looking to bring an unrelated technology into the mix when Django REST Framework fits the bill quite nicely already.
